version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: contest-postgres
    restart: always

    environment:
      POSTGRES_USER: contest_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: contest_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
